sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -t 2dazed/docker-react-training -f Dockerfile.dev .

script:
  - docker run -e CI=true 2dazed/docker-react-training npm run test



