sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -t 2dazed/docker-react-training -f Dockerfile.dev .

script:
  - docker run -e CI=true 2dazed/docker-react-training npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReactTraining"
  env: "DockerReactTraining-env"
  bucket_name: "elasticbeanstalk-us-east-2-179783938766"
  bucker_path: "DockerReactTraining"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
